baseURL = "https://devfest.duboutdumonde.bzh/"
languageCode = "fr-fr"
title = "DevFest du Bout du Monde 2020"
theme = "devfest-theme-hugo"


enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = "UA-XXXXXXXX-X"



[params]
    title = "DevFest du Bout du Monde 2020"
    date = "2020-02-28"
    description = "The DevFest, or 'Developers Festival', is a technical conferences for software developers. It is aimed to students, profesionals or simply curious technophile."
    images = ["/images/social-share.jpg"]
    email = "devfestduboutdumonde@gmail.com"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"
    copyright = "We ❤️️ crepes"
    cfpUrl = "https://conference-hall.io/public/event/dKQ0YcKw6aqEl37htjvD"
    subscriptionUrl = "http://eepurl.com/dps1j5"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"

[params.logos]
    jumbo = "/images/logos/devfest_color_text.png"
    header = "/images/logos/devfest_color_text.png"
    footer = "/images/logos/devfest_gray_text.png"


[languages]
[languages.en]
    weight = 1
    languageName = "gb"

[languages.fr]
    weight = 2
    languageName = "fr"

[languages.fr.params]
    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs et développeuses. Elle s'adresse aussi bien aux étudiant•e•s, aux professionnels ou tout simplement aux curieux et curieuses technophiles."

[taxonomies]
  tag = "tags"

[menu]
[[menu.main]]
    identifier = "CFP"
    name = "CFP"
    url = "https://conference-hall.io/public/event/dKQ0YcKw6aqEl37htjvD"
    weight = 200
    external = true


#...    


